-- MySQL Script generated by MySQL Workbench
-- Sun Apr  5 18:05:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema uniminutodb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `uniminutodb` ;

-- -----------------------------------------------------
-- Schema uniminutodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uniminutodb` DEFAULT CHARACTER SET utf8 ;
USE `uniminutodb` ;

-- -----------------------------------------------------
-- Table `uniminutodb`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniminutodb`.`countries` ;

CREATE TABLE IF NOT EXISTS `uniminutodb`.`countries` (
  `idcountry` INT NOT NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`idcountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniminutodb`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniminutodb`.`cities` ;

CREATE TABLE IF NOT EXISTS `uniminutodb`.`cities` (
  `idcitiy` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `idcountry` INT NOT NULL,
  PRIMARY KEY (`idcitiy`),
  CONSTRAINT `countryfk`
    FOREIGN KEY (`idcountry`)
    REFERENCES `uniminutodb`.`countries` (`idcountry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `city_UNIQUE` ON `uniminutodb`.`cities` (`city` ASC) VISIBLE;

CREATE INDEX `countryfk_idx` ON `uniminutodb`.`cities` (`idcountry` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `uniminutodb`.`occupations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniminutodb`.`occupations` ;

CREATE TABLE IF NOT EXISTS `uniminutodb`.`occupations` (
  `idoccupation` INT NOT NULL AUTO_INCREMENT,
  `occupation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idoccupation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniminutodb`.`identifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniminutodb`.`identifications` ;

CREATE TABLE IF NOT EXISTS `uniminutodb`.`identifications` (
  `ididentification` INT NOT NULL AUTO_INCREMENT,
  `reference` VARCHAR(45) NOT NULL,
  `type` ENUM('birth', 'younger', 'adult') NOT NULL,
  PRIMARY KEY (`ididentification`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `reference_UNIQUE` ON `uniminutodb`.`identifications` (`reference` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `uniminutodb`.`persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniminutodb`.`persons` ;

CREATE TABLE IF NOT EXISTS `uniminutodb`.`persons` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `postalCode` VARCHAR(20) NULL,
  `birthdate` DATETIME NOT NULL,
  `gender` ENUM('M', 'F', 'ND') NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `birthplace` INT NULL,
  `ididentification` INT NOT NULL,
  `idoccupation` INT NOT NULL,
  PRIMARY KEY (`idpersona`),
  CONSTRAINT `birthplacefk`
    FOREIGN KEY (`birthplace`)
    REFERENCES `uniminutodb`.`cities` (`idcitiy`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `occupationfk`
    FOREIGN KEY (`idoccupation`)
    REFERENCES `uniminutodb`.`occupations` (`idoccupation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `identificationfk`
    FOREIGN KEY (`ididentification`)
    REFERENCES `uniminutodb`.`identifications` (`ididentification`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `birthplacefk_idx` ON `uniminutodb`.`persons` (`birthplace` ASC) VISIBLE;

CREATE INDEX `occupationfk_idx` ON `uniminutodb`.`persons` (`idoccupation` ASC) VISIBLE;

CREATE UNIQUE INDEX `ididentification_UNIQUE` ON `uniminutodb`.`persons` (`ididentification` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
